# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
        # - run: npm test
        env:
          CI: true

      - name: Deploy
        # uses: easingthemes/ssh-deploy@v2.0.7
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN }}
          ARGS: -avz --delete --exclude='*.pyc'
          FOLDER: 'dist/'
          SERVER_IP: '39.107.118.88'
          USERNAME: 'root'
          SERVER_DESTINATION: '/usr/share/nginx/blog/'
